"""Pydantic models for hypothesis data."""

from datetime import datetime
from typing import Optional
from uuid import uuid4

from pydantic import BaseModel, Field


class ExperimentReference(BaseModel):
    """Reference to a past experiment that motivated the hypothesis."""
    experiment_name: str
    observation: str


class PaperReference(BaseModel):
    """Reference to an arXiv paper that motivated the hypothesis."""
    paper_title: str
    arxiv_id: str
    insight_used: str


class Motivation(BaseModel):
    """What motivated this hypothesis."""
    based_on_experiments: list[ExperimentReference] = Field(default_factory=list)
    based_on_papers: list[PaperReference] = Field(default_factory=list)


class ProposedChanges(BaseModel):
    """Proposed experimental changes."""
    model_type: str
    features: str
    augmentation: str
    training_modifications: str


class Hypothesis(BaseModel):
    """A research hypothesis generated by the agent."""
    id: str = Field(default_factory=lambda: str(uuid4()))
    title: str
    hypothesis_text: str
    motivation: Motivation
    proposed_changes: ProposedChanges
    expected_effect: str
    novelty_explanation: str
    strategy: str = ""
    generation_timestamp: str = Field(
        default_factory=lambda: datetime.now().isoformat()
    )
    status: str = "unverified"
    verification_metrics: Optional[dict] = None
    source_type: str = "generated"
    experiment_id: Optional[int] = None
    comments: list[dict] = Field(default_factory=list)

    def to_embedding_text(self) -> str:
        """Create text representation for embedding."""
        return (
            f"{self.title}. {self.hypothesis_text}. "
            f"Model: {self.proposed_changes.model_type}. "
            f"Features: {self.proposed_changes.features}. "
            f"Augmentation: {self.proposed_changes.augmentation}. "
            f"{self.proposed_changes.training_modifications}"
        )
